version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command:
            pip install --user -r requirements.txt
      - run:
          name: Running Dummy tests
          command:
            python test.py
      - store_test_results:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_test
