version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command:
            pip install --user -r requirements.txt
      - run:
          name: Running Dummy tests
          command:
            echo 'python test.py'
  run_dummy:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Dummy Job Running
          command:
            python test.py
workflows:
  build_test:
    jobs:
      - run_test
  main_build:
    jobs:
      - run_dummy
