version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python3.8.5
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command:
            pip install --user -r requirements.txt
workflows:
  build_test:
    jobs:
      - run_test
